name: Actualizar Jugadores

on:
  schedule:
    - cron: '*/5 * * * *'  # Ejecuta cada 30 minutos

jobs:
  update-players:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar Dependencias
        run: |
          pip install PyGithub

      - name: Ejecutar Script de Actualización
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python .github/scripts/update_players.py
