name: Update JSON on PR and run games

on:
  repository_dispatch:
    types: [pr_created]

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Ejecutar Script Python
      run: python new_repo.py ${{ github.event.client_payload.pr_user }} ${{ github.event.client_payload.pr_link }}
